### ISSUE TITLE
children prop is causing some type errors although it works correctly in runtime

### ISSUE THREAD

**Issue by joetifa2003** [elysiajs/elysia-html#10]
![image](https://github.com/elysiajs/elysia-html/assets/62658783/18a63d15-3d42-4d6b-be93-031d04caeb72)

**Comment by ethanniser** [comment]
![image](https://github.com/elysiajs/elysia-html/assets/100045248/3978544c-7094-4d1d-979b-a69826e65f75)
[kitajs/html](https://github.com/kitajs/html) has types that should solve this
we just need to reexport them

**Comment by arthurfiorette** [comment]
Hey @ethanniser & @SaltyAom. I was looking through the source code and seems that there are things that can better integrate with @kitajs/html and how JSX works in general... Would you mind on me opening a PR to improve them?

**Comment by joetifa2003** [comment]
import { PropsWithChildren } from "@kitajs/html";

I added the package as a dep just to import the type, because i found no way to import this from Elysia html

**Comment by joetifa2003** [comment]
Also i don't see a way to call @kitajs/html compile from this plugin

**Comment by ethanniser** [comment]
The plugin is just a couple days out of date with kita, if someone wants to make a pr it would not be that hard.

I might be able to later tonight
