### ISSUE TITLE
Using `Bun.build` will result into errors when running the output.

### ISSUE THREAD

**Issue by awilderink** [elysiajs/elysia-html#14]
If you build a project with `bun` using this package, you can't run the built file.

## How to reproduce
* Create a project using `elysia` and the `elysia-html` plugin.
* Compile the project
```
bun build --target=bun ./src/lambda.ts --outfile=lambda.js
``` 
* Try to run the project
```
bun lambda.js
```
* This will result into
```
32 | var require_html = __commonJS((exports, module) => {
33 |   __export(exports, {
34 |     toKebabCase: () => {
35 |       {
36 | 
37 |         return $toKebabCase;
                  ^
ReferenceError: Can't find variable: $toKebabCase
      at toKebabCase (/Users/awilderink/code/bun-lambda/lambda.js:37:15)
```

This could also be an issue with `bun build` or `@kitajs/html`.

**Comment by SeqSEE** [comment]
```ts
await Bun.build({
	entrypoints: ['./src/index.tsx'],
	outdir: './dist',
	target: 'bun',
})
```

Same issue for me using a `build.ts` file and `bun build.ts`

**Comment by awilderink** [comment]
I found the issue. `@kitajs/html` is imported through `require` statements. This should be fine, but `bun` probably builds this wrong (maybe an issue should be created but I'm not sure how to describe it). You can fix it by swapping the `require` statement for `import`s. I want to submit a PR but the repo won't let me.

Here are the changes

```ts
// index.ts
...
import { createElement, Fragment as F } from  '@kitajs/html'
globalThis.ElysiaJSX = createElement
// @ts-ignore
globalThis.ElysiaJSX.Fragment = Fragment

export const Fragment = F as unknown as Component 

export default html
...
```

and

```ts
// declaration.ts
// remove all of the following since they have been moved to index.ts (imports in declaration files will make them not globally available, see https://stackoverflow.com/a/51114250)

// @ts-ignore
const { createElement, Fragment } = require('@kitajs/html')

// @ts-ignore
globalThis.ElysiaJSX = createElement
// @ts-ignore
globalThis.ElysiaJSX.Fragment = Fragment
```

**Comment by arthurfiorette** [comment]
Hey @awilderink. After [this change](https://github.com/elysiajs/elysia-html/blob/5dee1438c0f19b1de6eed243e65b81fc39a3bf4c/src/index.ts#L2), does this problem still occurs?

**Comment by arthurfiorette** [comment]
Seems to be a issue with CJS syntax when using the bun bundler: https://github.com/oven-sh/bun/issues/5654

**Comment by arthurfiorette** [comment]
I'm releasing a fix for @kitajs/html asap. But it will keep incompatibilities with https://github.com/elysiajs/elysia/issues/178.
