### ISSUE TITLE
example returns pre-formatted string, not HTML

### ISSUE THREAD

**Issue by Lonitch** [elysiajs/elysia-html#29]
I'm trying out the following example of using the html plugin(0.7.3):

```
import { Elysia } from 'elysia'
import { html } from '@elysiajs/html' 

new Elysia()
    .use(html()) 
    .get('/', () => (
        <html lang="en">
            <head>
                <title>Hello World</title>
            </head>
            <body>
                <h1>Hello World</h1>
            </body>
        </html>
    ))
    .listen(3000)
```

The response header is `content-type | text/plain;charset=utf-8`, and the rendered HTML looks like the following:

![image](https://github.com/elysiajs/elysia-html/assets/29366226/fd803a5a-424d-4048-a35c-ac683c6591be)

The problem is solved when I switch back to 0.6.5.

**Comment by cool3rain** [comment]
Wrap your html code in backtick.

`
            <html lang='en'>
                <head>
                    <title>Hello World</title>
                </head>
                <body>
                    <h1>Hello World</h1>
                </body>
            </html>`

**Comment by Lonitch** [comment]
@arthurfiorette, I tried that one before switch back to 0.6.5, and it didn't work for me. my bun ver. is 1.0.0. Below is what I have in my `package.json`:

```
"dependencies": {
    "@editorjs/editorjs": "^2.28.0",
    "@editorjs/header": "^2.7.0",
    "@editorjs/image": "^2.8.1",
    "@editorjs/link": "^2.5.0",
    "@editorjs/list": "^1.8.0",
    "@elysiajs/html": "^0.6.5",
    "@elysiajs/static": "^0.6.0",
    "@kitajs/html": "^3.0.2",
    "@kitajs/ts-html-plugin": "^1.3.0",
    "@material-ui/core": "^4.12.4",
    "@t3-oss/env-core": "^0.7.0",
    "@types/markdown-it": "^13.0.1",
    "@types/react": "^18.2.28",
    "beth-stack": "^0.0.34",
    "elysia": "latest",
    "markdown-it": "^13.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "bun-types": "latest",
    "typescript": "latest"
  },
```

**Comment by arthurfiorette** [comment]
So your problem was outdated bun?

**Comment by Lonitch** [comment]
No, `bun update` updates `elysia`. My bun ver. remains at `1.0.0`.
