### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by W2Wizard** [elysiajs/elysia-html#3]
I don't know if I am just missing the obvious here but I basically did exactly what the example showed on a fresh new project.

All the documentation shows is this example and so I don't know if anything new was introduced without updating docs or if it something broke between `0.5.2` and `0.6.0`

This does not occur on version `0.5.2`, where it all just works without any errors.

```ts
// Index.ts
import { Elysia } from 'elysia'
import { html } from '@elysiajs/html'

const page = `<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
</html>`

const app = new Elysia()
    .use(html()) // <= Errors here
    .get('/', () => page)
    .get('/html', ({ html }) => html(page))
    .listen(8080)
```

I get the following error:
```txt
Argument of type 'Elysia<{ path: ""; store: {}; error: {}; request: { sanitize: typeof sanitize; html(value: string): Response; }; schema: {}; meta: { schema: {}; defs: {}; exposed: {}; }; }>' is not assignable to parameter of type 'MaybePromise<(app: Elysia<ElysiaInstance>) => MaybePromise<Elysia<any>>> | Promise<{ default: (elysia: Elysia<any>) => MaybePromise<...>; }>'
```

**Comment by thekorn** [comment]
for me this is working now, see https://github.com/elysiajs/elysia-html/issues/4#issuecomment-1722389328

**Comment by t0mri** [comment]
it is fixed now!
