### ISSUE TITLE
type errors for iframe attributes in tsx files

### ISSUE THREAD

**Issue by ariviom** [elysiajs/elysia-html#41]
Adding iframe elements to a tsx file produces type errors for supported attributes like allow or frameborder.

"Type '{ width: string; height: string; src: string; title: string; frameborder: string; allow: string; allowfullscreen: true; }' is not assignable to type 'HtmlIFrameTag'.
  Property 'frameborder' does not exist on type 'HtmlIFrameTag'."

**Minimal reproduction:**
Init new bun elysia project
` bun create elysia app `

Update tsconfig.json
```
// tsconfig.json
{
    "compilerOptions": {
        "jsx": "react",
        "jsxFactory": "Html.createElement",
        "jsxFragmentFactory": "Html.Fragment"
    }
}
```

Update index.tsx file:
```
import { Elysia } from 'elysia'
import { html } from '@elysiajs/html'

new Elysia()
    .use(html())
    .get('/jsx', () => (
        <html lang='en'>
            <head>
                <title>Hello World</title>
            </head>
            <body>
                <h1>Hello World</h1>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=RclVnENrgMEt3tD9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </body>
        </html>
    ))
    .listen(3000)
```

**Comment by arthurfiorette** [comment]
Hey @ariviom, this is an issue with @kitajs/html package. I'll fix it and release a new version.

_@SaltyAom I'm technically maintaining this specific package for a while, would you mind giving me permissions to transfer issues to @kitajs/html repo?_
