### ISSUE TITLE
sanitize feature is implemented incorrectly

### ISSUE THREAD

**Issue by peterje** [elysiajs/elysia-html#8]
DOMPurify, when run on a server, requires an external DOM implementation such has JSDOM. The current initialization of `sanitize` will always be undefined for that reason. Correct usage:

```ts

import createDOMPurify from 'dompurify'
import {JSDOM} from 'jsdom'

const {sanitize} = createDOMPurify(new JSDOM('').window)

```

**Comment by arthurfiorette** [comment]
With 0.6.6 there's a new way of sanitizing user input.
https://github.com/kitajs/html#sanitization
