### ISSUE TITLE
Cannot find name 'Html'

### ISSUE THREAD

**Issue by lukebrider-woolard-cgi** [elysiajs/elysia-html#96]
I'm trying to set up a new TypeScript project using ElysiaJS but I'm failing at the first hurdle. I'm getting typescript errors and the Elysia server fails with an internal error. The error presents as `Cannot find name 'Html'. Did you mean 'html'?` on all jsx lines. I feel like I've followed the docs exactly but I must have done something wrong...

index.tsx file:
![image](https://github.com/user-attachments/assets/b1d78508-19d8-46bd-b76e-94df02d8e7f8)

package.json file:
![image](https://github.com/user-attachments/assets/80672e9c-ae9f-4c44-9b3b-c5fb07eb624a)

Part of tsconfig.json file:
![image](https://github.com/user-attachments/assets/070e8653-753e-4ecf-90a9-d17bfea24766)

**Comment by lukebrider-woolard-cgi** [comment]
bun pm ls output:
```
/home/lbrider-woolard/repos/encyclopaedia node_modules (44)
├── @elysiajs/html@1.1.0
├── bun-types@1.1.24
├── elysia@1.1.7
└── typescript@5.5.4
```

**Comment by TeraNovaLP** [comment]
@lukebrider-woolard-cgi Try to add this import to your file:
```ts
import { Html } from "@elysiajs/html";
```

It is important to that it starts with an uppercase letter.

**Comment by lukebrider-woolard-cgi** [comment]
> @lukebrider-woolard-cgi Try to add this import to your file:
> 
> ```ts
> import { Html } from "@elysiajs/html";
> ```
> 
> It is important to that it starts with an uppercase letter.

It seems you actually need both, despite the documentation website suggesting otherwise:
![image](https://github.com/user-attachments/assets/9b501621-c92b-46b1-9ece-e2230b508ed0)
